# Generated by Django 4.1.1 on 2022-10-03 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='weigth',
            new_name='weight',
        ),
    ]
